// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKHT37X0fS-E2HNedmKO9DuZEg0wxPCVQ',
    appId: '1:796573695792:web:aab6eae8b5f458f7a592f5',
    messagingSenderId: '796573695792',
    projectId: 'test-61354',
    authDomain: 'test-61354.firebaseapp.com',
    storageBucket: 'test-61354.firebasestorage.app',
    measurementId: 'G-3ZBKRDDJC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1QFNlLvg8J8X8GHpSdYFjBpTeOFC2cgc',
    appId: '1:796573695792:android:2bb41d13e8195791a592f5',
    messagingSenderId: '796573695792',
    projectId: 'test-61354',
    storageBucket: 'test-61354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP6GB5hX8-o7wfn8bbEPijn7tf4hII5rg',
    appId: '1:796573695792:ios:7a2965e1d29630eba592f5',
    messagingSenderId: '796573695792',
    projectId: 'test-61354',
    storageBucket: 'test-61354.firebasestorage.app',
    iosBundleId: 'com.example.payment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP6GB5hX8-o7wfn8bbEPijn7tf4hII5rg',
    appId: '1:796573695792:ios:7a2965e1d29630eba592f5',
    messagingSenderId: '796573695792',
    projectId: 'test-61354',
    storageBucket: 'test-61354.firebasestorage.app',
    iosBundleId: 'com.example.payment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKHT37X0fS-E2HNedmKO9DuZEg0wxPCVQ',
    appId: '1:796573695792:web:4c230d5d4ed6a598a592f5',
    messagingSenderId: '796573695792',
    projectId: 'test-61354',
    authDomain: 'test-61354.firebaseapp.com',
    storageBucket: 'test-61354.firebasestorage.app',
    measurementId: 'G-N9LHF5VSTP',
  );
}
